apiVersion: v1
appVersion: V.0.1
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
name: conduction-ui
version: 0.1.0
home: www.conduction.nl
icon: www.conduction.nl