{{ if or (eq .Values.settings.type "application") .Values.settings.web }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        # add an annotation indicating the issuer to use.
        #    cert-manager.io/acme-challenge-type: http01
        #    cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    name: {{ .Values.settings.name }}-{{ .Values.settings.env }}-ingress
    labels:
        app.kubernetes.io/name: {{ .Values.settings.name }}-ingress
        app.kubernetes.io/part-of: {{ .Values.settings.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    #  tls: 
    #  - hosts: 
    #    - {{ $.Values.settings.domain }}
    #    secretName: {{ template "fullname" . }}
    rules:
        - host: conduction.nl
          http:
              paths:
                  - path: /(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}-app
                        servicePort: 80
                  - path: /api/(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}
                        servicePort: 80
                  - path: /api(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}
                        servicePort: 80
        - host: www.conduction.nl
          http:
              paths:
                  - path: /(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}-app
                        servicePort: 80
                  - path: /api/(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}
                        servicePort: 80
                  - path: /api(.*)
                    backend:
                        serviceName: {{ $.Values.settings.name }}
                        servicePort: 80
  {{ end }}
